update installer

diff --git a/install b/install
--- a/install
+++ b/install
@@ -4,7 +4,7 @@ PREFIX="${PREFIX:-/usr/local}"
 bin_dir="${PREFIX}"
 man_dir="${PREFIX}/share"
 
-fail(){ [[ $1 ]] && printf '%s\n' "failed to $1"; exit 1;}
+fail(){ [[ $1 ]] && printf '%s\n' "failed: $1"; exit 1;}
 success(){ printf '%s\n' "successfully $1";}
 
 install(){
@@ -21,13 +21,13 @@ uninstall(){
 }
 
 copy(){
-	dest="${PREFIX}/$1"
-	[[ "$dest" -ot "$1" || ! -a $dest ]] || fail "not newer"
+	local dest="${PREFIX}/$1"
+	[[ "$dest" -ot "$1" || ! -a $dest ]] || fail
 	cp -rf $1 "${dest//man\//share\/man/}" || fail $_
 }
 
 remove(){
-	dest="${PREFIX}/$1"
+	local dest="${PREFIX}/$1"
 	[[ "$dest" ]] || return 1
 	rm "${dest//man\//share\/man/}" || fail $_
 }
